authors:
  Sylian:
     name: Sylian (Morten)
     description: Content creator & Developer
     avatar: https://avatars.githubusercontent.com/u/14792697?s=400&u=d7fb24f102bb11b0e10c966724fbc3a9f1a128db&v=4
     url: https://www.youtube.com/@DEVSylian